### ISSUE TITLE
hydro-devel out of sync

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_msgs#104]
I did a fresh pull of hydro-devel on a different machine, and it seems like there's been a force push to the hydro-devel branch that has gotten the branch out of sync.

On my machine where I pulled a few days ago:

```
# On branch hydro-devel
# Your branch is ahead of 'origin/hydro-devel' by 21 commits.
#
nothing to commit (working directory clean)
```

The current hydro-devel seems to be 1 commit ahead and 39 commits behind indigo. Could one of you guys resync it after testing?

**Comment by piyushk** [comment]
I think this commit in hydro-devel c350851e379cee1fcb66869e8346e6006cd0ee74 makes things work for me.

**Comment by jihoonl** [comment]
There are some updates in rocon. I will resync both branches soon.

**Comment by jihoonl** [comment]
Done. You may need to clone as well as software farm has been developed. https://github.com/robotics-in-concert/rocon_concert/pull/255

https://github.com/robotics-in-concert/concert_software_farm

**Comment by piyushk** [comment]
hydro-devel in rocon_msgs still seems to be at the old commit, though the other repos seem to have been updated.

**Comment by jihoonl** [comment]
Oops. I forgot to sync msgs. It has been as of now.
