### ISSUE TITLE
Can you make it also for Java?

### ISSUE THREAD

**Issue by talregev** [robotics-in-concert/rocon_msgs#106]
I successfully compile this rocon_msgs, but it compile to c++, python messages .
I need it at java compilation for the project:
https://github.com/robotics-in-concert/rocon_rosjava_core

I was searching, and there is maven repository that hold rocon_msg in old version (0.6.5):
https://github.com/rosjava/rosjava_mvn_repo/tree/master/org/ros/rosjava_messages/rocon_app_manager_msgs
https://github.com/rosjava/rosjava_mvn_repo/tree/master/org/ros/rosjava_messages/rocon_msgs
https://github.com/rosjava/rosjava_mvn_repo/tree/master/org/ros/rosjava_messages/rocon_std_msgs
https://github.com/rosjava/rosjava_mvn_repo/tree/master/org/ros/rosjava_messages/concert_msgs

can you compile it to java also? or explain to me how to do it?

Thanks,
Tal.

**Comment by stonier** [comment]
You should be able to drop this repo into a rosjava workspace and compile according to the [wiki](http://wiki.ros.org/rosjava/Tutorials/indigo/RosJava%20Message%20Artifacts) instructions on indigo.

They don't have any esoteric dependencies (other than e.g. `std_msgs` and `std_srvs`). If they do, let me know.
