### ISSUE TITLE
Rename rocon_app_manager_msgs to app_manager_msgs

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_msgs#22]
To shorten the name a bit. `app_manager_msgs` seems not yet been taken.

**Comment by stonier** [comment]
Was in the middle of moving everything across to rocon_xxx just for uniqueness and conformity.

Got so much depending on these msgs though, would be a pain in the ass to go track down everything. For this one too, would mean rebuilding and redeploying the android apps.

Unless there's a big reason to move, (or I find a volunteer to make the changes and chase bugs!), I'm ok with them as they are.
