### ISSUE TITLE
scheduler_msgs: suggested small API improvements 

### ISSUE THREAD

**Issue by jack-oquin** [robotics-in-concert/rocon_msgs#41]
Based on experience working with this package, there are some minor changes I'd like to make at some point. 

Right now, I am working with the hydro-devel version, but I'll provide a pull request for this when it would not be disruptive to merge. Meanwhile, this issue provides a focal point for discussing proposed changes.
- Rename `AllocateResources.resources` -> `AllocateResources.requests` to make it consistent with `SchedulerFeedback`. That inconsistency is confusing.
- Make `priority` fields signed: `int16` instead of `uint16`. We have not yet decided on the exact meaning, but my guess is that the default setting of zero should be in the middle of the priority range, not at the beginning.

**Comment by jack-oquin** [comment]
On further investigation, the `AllocateResources` and `SchedulerFeedback` messages are essentially identical. They should be merged into a single common scheduler message for both requests and feedback.

**Comment by jack-oquin** [comment]
The previous commit added the `Request.RESERVED` status for reserving a resource at some future time, expressed by the `availability` field, which the scheduler can update if it knows a better estimate. 

Still missing to make this work: an estimate of the _duration_ that the requested resource will be held.

**Comment by stonier** [comment]
No problems with any of this from my perspective. Will raise some use cases that don't fit exactly as I go through this over the next couple of days. Feel free to close the issue.
