### ISSUE TITLE
scheduler_msgs: remove deprecated AllocateResources and SchedulerFeedback messages

### ISSUE THREAD

**Issue by jack-oquin** [robotics-in-concert/rocon_msgs#46]
This should not be done until after existing users have migrated from those messages to the [SchedulerRequests](https://github.com/robotics-in-concert/rocon_msgs/blob/hydro-devel/scheduler_msgs/msg/SchedulerRequests.msg) message.

**Comment by stonier** [comment]
There are other users than us?

I've just started integrating your code for the first time - the Requester part is in so far and am ok if the depracations disappear.

**Comment by jack-oquin** [comment]
No, just your project. 

If it will not cause any disruption, I'll remove them soon.

**Comment by jack-oquin** [comment]
I'd also like to remove the `SchedulerRequests.priority` field. Now that every `Request` has a priority, that field is no longer used. Leaving it there would be confusing.

**Comment by stonier** [comment]
Removing the higher priority flag - I concur.

**Comment by stonier** [comment]
Removed the priority flag in dea03cecc213f53c901229c40777c7ff5dd0fb9b

**Comment by stonier** [comment]
Also removed deprecated messages in 6a2be3dd63f3361105ef76ee8940aaa4d5d71071
