### ISSUE TITLE
scheduler_msgs and rocon_std_msgs: please release to Hydro

### ISSUE THREAD

**Issue by jack-oquin** [robotics-in-concert/rocon_msgs#57]
It would be more convenient to me if reasonable versions of **scheduler_msgs** and **rocon_std_msgs** could be added to the current Hydro release of **rocon_msgs**. Otherwise **rocon_scheduler_requests** fails its devel tests and cannot generate API documentation in the wiki because those packages are missing.

I don't believe it will break any old Hydro code, because they are new packages. The dependency on **concert_msgs** is unused and should be removed, anyway.
- If this is acceptable, I will provide a pull request to update the hydro branch.
- If it's not worth the hassle, please just close this issue.

**Comment by stonier** [comment]
That'd be fine Jack, send us the pull request and I'll fire up a deb.

**Comment by jack-oquin** [comment]
I fixed a couple of minor problems I noticed with the hydro-devel branch, too. 

That is why there are two pull requests.

**Comment by stonier** [comment]
rosdistro awaiting a pull request for the new package specification, will bloom it as soon as the changes are in.

**Comment by stonier** [comment]
It's in shadow-fixed.

**Comment by jack-oquin** [comment]
Thanks!

Now my unit tests run automatically after every commit.

The wiki page should also generate documentation successfully some time in the next few days.
