### ISSUE TITLE
scheduler_msgs: revise Request.status labels

### ISSUE THREAD

**Issue by jack-oquin** [robotics-in-concert/rocon_msgs#60]
This issue is a forum for discussing scheduler request status updates. The proposed changes will be made in two steps:
1. define new labels; deprecate some old ones
2. remove deprecated labels once users have updated

The current proposal is:
- rename RELEASED status to CANCELED.
- rename RELEASING status to CANCELING.
- eliminate ABORTED status: use CANCELED instead.
- eliminate PREEMPTED status: use CANCELED instead.
- eliminate REJECTED status: use CANCELED instead.

With this proposal, CANCELED becomes the only terminal state. Once acknowledged, the canceled request will be deleted.

As best I can tell, the abort() and reject() events can handled via preempt(), simplifying the state transitions considerably.

**Comment by jack-oquin** [comment]
New transition graph documentation:
- http://farnsworth.csres.utexas.edu/docs/rocon_scheduler_requests/html/transitions.html

**Comment by stonier** [comment]
Looks good Jack. I actually don't have anything to discuss here :)

**Comment by jack-oquin** [comment]
Sure.

I am not yet ready to commit this change, but wanted to put the ideas in writing where they will be handy when the time is right. 

Maybe something more will come up after further development. If it does, let's add it here.

**Comment by jack-oquin** [comment]
I closed pull request #64 so we can consider additional changes. 

I want to only make one update for this go-around.

**Comment by jack-oquin** [comment]
The previous commit renames the terminal status to CLOSED.

It also adds a `reason` field to supplement the request status, which allows the scheduler to tell the requester why a request was queued, preempted or closed. I want to add that now, because we really can't start using it until it has been released.

**Comment by jack-oquin** [comment]
I tried to take out the backwards compatibility logic in my code (utexas-bwi/rocon_scheduler_requests#21). The pre-release tests build dependencies from source, so they work. 

But the devel tests install binary dependency packages, so they fail on the build farm. So, I need a new hydro branch release to avoid having to put back the compatibility logic.

Would that be OK?

**Comment by stonier** [comment]
> Would that be OK?

Sure. Just send a pull request and I'll bump a new release anytime. I have scripts which mean it takes all of 5mins for me to do.

**Comment by jack-oquin** [comment]
The updates are already merged from #67, I just need a Hydro release.
