### ISSUE TITLE
scheduler_msgs: do we need to track each request time separately?

### ISSUE THREAD

**Issue by jack-oquin** [robotics-in-concert/rocon_msgs#63]
Right now there is no need, but the question remains open.

**Comment by jack-oquin** [comment]
Some schedulers will want to track when they first saw a request or when it was last updated. Others may not care.

But, I cannot see why that information would need to be included in the message protocol.

**Comment by stonier** [comment]
I haven't got a use case for tracking times yet.

**Comment by jack-oquin** [comment]
Assuming the answer is "no". 

Re-open if that is wrong.
