### ISSUE TITLE
scheduler_msgs: add messages for reporting status of known resources

### ISSUE THREAD

**Issue by jack-oquin** [robotics-in-concert/rocon_msgs#68]
To avoid mixing these changes into the Request message update, I am working on them in the resource_msgs branch of my rocon_msgs fork.

The current design is to add two messages. For now, I am calling them **KnownResources** and **CurrentStatus**.

**Comment by jack-oquin** [comment]
New messages are here right now:
- [KnownResources](https://github.com/jack-oquin/rocon_msgs/blob/resource_msgs/scheduler_msgs/msg/KnownResources.msg)
- [CurrentStatus](https://github.com/jack-oquin/rocon_msgs/blob/resource_msgs/scheduler_msgs/msg/CurrentStatus.msg)

**Comment by stonier** [comment]
These look fine jack.

**Comment by stonier** [comment]
I think we're done here...closing. @jack-oquin reopen if there's more.
