### ISSUE TITLE
scheduler_msgs: add Request.INVALID reason code for canceling

### ISSUE THREAD

**Issue by jack-oquin** [robotics-in-concert/rocon_msgs#70]

**Comment by stonier** [comment]
Some commits relevant to this: 854120dc1dc3c0b12a0422046ff1a87d2cd9733b f23bc8885eb41cc0fe866dc4db01329fa11510e6 af874de86d80933fa935e7e3d757181f50adccc4.

I think we're at a good point with this - @jack-oquin anymore to do?

**Comment by jack-oquin** [comment]
No, it's done.
