### ISSUE TITLE
Incompatible App List

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_msgs#86]
@stonier  @bit-pirate 
Does it need to be App[]? How about make them as just string[] which contains resource name?

If an app is invalid or unavailable, it is hard to instantiate Rapp object.

**Comment by bit-pirate** [comment]
> Does it need to be App[]? How about make them as just string[] which contains resource name?

:+1:

**Comment by stonier** [comment]
Im ok with that too
